/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of PqQueryhistoricalpayments400Response
 */
interface PqQueryhistoricalpayments400Response {
  /** The type of error. */
  errorName: string;
  /** A description of the error */
  message: string;
  additionalProperties?: Record<string, unknown>;
}

export class PqQueryhistoricalpayments400ResponseError extends ApiError<
  PqQueryhistoricalpayments400Response
> {}
