/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of PqQuerybydaterange400Response
 */
interface PqQuerybydaterange400Response {
  /** The type of error. */
  errorName: string;
  /** A description of the error. */
  message: string;
}

export class PqQuerybydaterange400ResponseError extends ApiError<
  PqQuerybydaterange400Response
> {}
