/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { acceptEnumSchema } from '../../models/acceptEnum.js';
import { number, object, optional, string } from '../../schema.js';

export const queryByDateRangeMetadataRequestSchema = object({
  accept: ['Accept', acceptEnumSchema],
  startDate: ['startDate', string()],
  endDate: ['endDate', string()],
  pageSize: ['pageSize', optional(number())],
  currency: ['currency', optional(string())],
  minAmount: ['minAmount', optional(number())],
  maxAmount: ['maxAmount', optional(number())],
  last4Digits: ['last4Digits', optional(string())],
  entityReferences: ['entityReferences', optional(string())],
  receivedEvents: ['receivedEvents', optional(string())],
  transactionReference: ['transactionReference', optional(string())],
});

export const retrieveByPaymentIdMetadataRequestSchema = object({
  accept: ['Accept', string()],
  paymentId: ['paymentId', string()],
});

export const queryArchivedPaymentsMetadataRequestSchema = object({
  accept: ['Accept', string()],
  transactionReference: ['transactionReference', string()],
  entityReference: ['entityReference', string()],
});

