/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  string,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const queryByDateRangeMetadataRequestSchema = typedExpandoObject(
  {
    accept: ['Accept', string()],
    startDate: ['startDate', string()],
    endDate: ['endDate', string()],
    pageSize: ['pageSize', optional(number())],
    currency: ['currency', optional(string())],
    minAmount: ['minAmount', optional(number())],
    maxAmount: ['maxAmount', optional(number())],
    last4Digits: ['last4Digits', optional(string())],
    entityReferences: ['entityReferences', optional(string())],
    receivedEvents: ['receivedEvents', optional(string())],
    transactionReference: ['transactionReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);

export const retrieveByPaymentIdMetadataRequestSchema = typedExpandoObject(
  { accept: ['Accept', string()], paymentId: ['paymentId', string()] },
  'additionalProperties',
  optional(unknown())
);

export const queryArchivedPaymentsMetadataRequestSchema = typedExpandoObject(
  {
    accept: ['Accept', string()],
    transactionReference: ['transactionReference', string()],
    entityReference: ['entityReference', string()],
  },
  'additionalProperties',
  optional(unknown())
);

