/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpClientOptions } from './clientAdapter.js';
import { PartialLoggingOptions } from './core.js';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  basicAuthCredentials?: {
    username: string;
    password: string;
  };
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
  logging?: PartialLoggingOptions;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
  Environment2 = 'environment2',
}

export function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.PAYMENT_QUERIES_LIB_ENVIRONMENT;
  const timeout = process.env.PAYMENT_QUERIES_LIB_TIMEOUT;
  const basicAuthUserName = process.env.PAYMENT_QUERIES_LIB_BASIC_AUTH_USER_NAME;
  const basicAuthPassword = process.env.PAYMENT_QUERIES_LIB_BASIC_AUTH_PASSWORD;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (basicAuthUserName !== undefined && basicAuthPassword !== undefined) {
    config.basicAuthCredentials = {
      username: basicAuthUserName,
      password: basicAuthPassword,
    };
  }

  return config;
}
