/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Accept
 */
export enum Accept {
  EnumApplicationvndworldpaypaymentqueriesv1Haljson = 'application/vnd.worldpay.payment-queries-v1.hal+json',
}

/**
 * Schema for Accept
 */
export const acceptSchema: Schema<Accept> = stringEnum(Accept);
