/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AcceptEnum
 */
export enum AcceptEnum {
  EnumApplicationvndworldpaypaymentqueriesv1haljson = 'application/vnd.worldpay.payment-queries-v1.hal+json',
}

/**
 * Schema for AcceptEnum
 */
export const acceptEnumSchema: Schema<AcceptEnum> = stringEnum(AcceptEnum);
