/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountUpdaterMessage
 */
export enum AccountUpdaterMessage {
  EnumTheMerchantIsNotRegisteredInTheUpdateProgram = 'The merchant is not registered in the update program',
  EnumTheAccountNumberWasChanged = 'The account number was changed',
  EnumTheAccountWasClosed = 'The account was closed',
  EnumTheExpiryWasChanged = 'The expiry was changed',
  EnumTheIssuingBankDoesNotParticipateInTheUpdateProgram = 'The issuing bank does not participate in the update program',
  EnumContactTheCardholderForUpdatedInformation = 'Contact the cardholder for updated information',
  EnumNoMatchFound = 'No match found',
  EnumNoChangesFound = 'No changes found',
}

/**
 * Schema for AccountUpdaterMessage
 */
export const accountUpdaterMessageSchema: Schema<AccountUpdaterMessage> = stringEnum(
  AccountUpdaterMessage
);
