/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AuthorizationTypeEnum
 */
export enum AuthorizationTypeEnum {
  Authorization = 'authorization',
  Sale = 'sale',
}

/**
 * Schema for AuthorizationTypeEnum
 */
export const authorizationTypeEnumSchema: Schema<AuthorizationTypeEnum> = stringEnum(
  AuthorizationTypeEnum
);
