/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AuthorizationType1
 */
export enum AuthorizationType1 {
  Authorization = 'authorization',
  Sale = 'sale',
}

/**
 * Schema for AuthorizationType1
 */
export const authorizationType1Schema: Schema<AuthorizationType1> = stringEnum(
  AuthorizationType1
);
