/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AuthorizationTimedOut {
  /** Your authorization request timed out. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  additionalProperties?: Record<string, unknown>;
}

export const authorizationTimedOutSchema: Schema<AuthorizationTimedOut> = typedExpandoObject(
  {
    eventName: ['eventName', string()],
    timestamp: ['timestamp', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
