/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AuthorizationType
 */
export enum AuthorizationType {
  Authorization = 'authorization',
  Sale = 'sale',
}

/**
 * Schema for AuthorizationType
 */
export const authorizationTypeSchema: Schema<AuthorizationType> = stringEnum(
  AuthorizationType
);
