/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AuthorizationType1Enum
 */
export enum AuthorizationType1Enum {
  Authorization = 'authorization',
  Sale = 'sale',
}

/**
 * Schema for AuthorizationType1Enum
 */
export const authorizationType1EnumSchema: Schema<AuthorizationType1Enum> = stringEnum(
  AuthorizationType1Enum
);
