/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface CancellationFailed {
  /** Your cancellation request failed. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** Unique identifier generated by us for a single instance of an interaction (command) with the Worldpay API. */
  commandId?: string;
}

export const cancellationFailedSchema: Schema<CancellationFailed> = object({
  eventName: ['eventName', string()],
  timestamp: ['timestamp', optional(string())],
  commandId: ['commandId', optional(string())],
});
