/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CancellationRequested {
  /** Worldpay has received your cancellation request. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** Unique identifier generated by us for a single instance of an interaction (command) with the Worldpay API. */
  commandId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const cancellationRequestedSchema: Schema<CancellationRequested> = typedExpandoObject(
  {
    eventName: ['eventName', string()],
    timestamp: ['timestamp', optional(string())],
    commandId: ['commandId', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
