/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';
import { FundingType, fundingTypeSchema } from './fundingType.js';
import { Number, numberSchema } from './number.js';

/** An object that contains information about the card used. */
export interface Card1 {
  /** An object that contains information about the card number. */
  number?: Number;
  /** The expiry date of the card or network token (where the supplied paymentInstrument was `card/wallet+applepay`, `card/wallet+googlepay`, `card/networkToken`, `card/networkToken+applepay` or `card/networkToken+googlepay`). */
  expiryDate?: ExpiryDate;
  /** How the card is funded. */
  fundingType?: FundingType;
  /** The card brand that the transaction was processed with. Sometimes referred to as the network or scheme. */
  brand?: string;
  additionalProperties?: Record<string, unknown>;
}

export const card1Schema: Schema<Card1> = typedExpandoObject(
  {
    number: ['number', optional(lazy(() => numberSchema))],
    expiryDate: ['expiryDate', optional(lazy(() => expiryDateSchema))],
    fundingType: ['fundingType', optional(fundingTypeSchema)],
    brand: ['brand', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
