/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Category, categorySchema } from './category.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';
import { FundingType, fundingTypeSchema } from './fundingType.js';
import { Number, numberSchema } from './number.js';

/** An object that contains information about the card used. */
export interface Card {
  /** An object that contains information about the card number. */
  number?: Number;
  /** Whether the card is classed as a consumer card or a card for commercial use. */
  category?: Category;
  /** The [ISO 3166-1 Alpha-2 format](/products/reference/supported-countries-currencies#iso-country-codes) country code that the card was issued in. May return `N/A` where the country is unknown. */
  countryCode?: string;
  /** The expiry date of the card or network token (where the supplied paymentInstrument was `card/wallet+applepay`, `card/wallet+googlepay`, `card/networkToken`, `card/networkToken+applepay` or `card/networkToken+googlepay`). */
  expiryDate?: ExpiryDate;
  /** The name of the card issuer. */
  issuerName?: string;
  /** How the card is funded. */
  fundingType?: FundingType;
  /** The card brand that the transaction was processed with. Sometimes referred to as the network or scheme. */
  brand?: string;
  /** The payment account reference (PAR) is a non-financial reference that uniquely identifies the underlying cardholder account. This allows you to correlate payments made from the same account with differing instruments (e.g. `card/plain` and `card/wallet+applepay`), where the same account funds the transaction. A PAR cannot be used to initiate a payment. */
  paymentAccountReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const cardSchema: Schema<Card> = typedExpandoObject(
  {
    number: ['number', optional(lazy(() => numberSchema))],
    category: ['category', optional(categorySchema)],
    countryCode: ['countryCode', optional(string())],
    expiryDate: ['expiryDate', optional(lazy(() => expiryDateSchema))],
    issuerName: ['issuerName', optional(string())],
    fundingType: ['fundingType', optional(fundingTypeSchema)],
    brand: ['brand', optional(string())],
    paymentAccountReference: ['paymentAccountReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
