/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, unknown } from '../schema.js';
import { Number3, number3Schema } from './number3.js';

/** An object that contains information about the card used. */
export interface Card3 {
  /** An object that contains information about the card number. */
  number?: Number3;
  /** An object that contains information about the brand. The brand values can be Visa, Mastercard etc. */
  brand?: unknown;
}

export const card3Schema: Schema<Card3> = object({
  number: ['number', optional(lazy(() => number3Schema))],
  brand: ['brand', optional(unknown())],
});
