/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Category
 */
export enum Category {
  Commercial = 'commercial',
  Consumer = 'consumer',
}

/**
 * Schema for Category
 */
export const categorySchema: Schema<Category> = stringEnum(Category);
