/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CategoryEnum
 */
export enum CategoryEnum {
  Commercial = 'commercial',
  Consumer = 'consumer',
}

/**
 * Schema for CategoryEnum
 */
export const categoryEnumSchema: Schema<CategoryEnum> = stringEnum(
  CategoryEnum
);
