/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Payment, paymentSchema } from './payment.js';

export interface Embedded {
  /** Array of payments within the date range. */
  payments?: Payment[];
  additionalProperties?: Record<string, unknown>;
}

export const embeddedSchema: Schema<Embedded> = typedExpandoObject(
  { payments: ['payments', optional(array(lazy(() => paymentSchema)))] },
  'additionalProperties',
  optional(unknown())
);
