/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Payment, paymentSchema } from './payment.js';

export interface Embedded {
  /** Array of payments within the date range. */
  payments?: Payment[];
}

export const embeddedSchema: Schema<Embedded> = object({
  payments: ['payments', optional(array(lazy(() => paymentSchema)))],
});
