/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Payment1, payment1Schema } from './payment1.js';

export interface Embedded1 {
  /** Array of payments. */
  payments?: Payment1[];
  additionalProperties?: Record<string, unknown>;
}

export const embedded1Schema: Schema<Embedded1> = typedExpandoObject(
  { payments: ['payments', optional(array(lazy(() => payment1Schema)))] },
  'additionalProperties',
  optional(unknown())
);
