/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import { Message, messageSchema } from './message.js';
import { Name, nameSchema } from './name.js';

/** All Failed events return error object with name and message. */
export interface Error {
  /** Example values are, */
  name?: Name;
  /** Example values are, */
  message?: Message;
  additionalProperties?: Record<string, unknown>;
}

export const errorSchema: Schema<Error> = typedExpandoObject(
  {
    name: ['name', optional(nameSchema)],
    message: ['message', optional(messageSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
