/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { MessageEnum, messageEnumSchema } from './messageEnum.js';
import { NameEnum, nameEnumSchema } from './nameEnum.js';

/** All Failed events return error object with name and message. */
export interface Error {
  /** Example values are, */
  name?: NameEnum;
  /** Example values are, */
  message?: MessageEnum;
}

export const errorSchema: Schema<Error> = object({
  name: ['name', optional(nameEnumSchema)],
  message: ['message', optional(messageEnumSchema)],
});
