/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The expiry date of the card or network token (where the supplied paymentInstrument was `card/wallet+applepay`, `card/wallet+googlepay`, `card/networkToken`, `card/networkToken+applepay` or `card/networkToken+googlepay`). */
export interface ExpiryDate {
  month?: number;
  year?: number;
  additionalProperties?: Record<string, unknown>;
}

export const expiryDateSchema: Schema<ExpiryDate> = typedExpandoObject(
  { month: ['month', optional(number())], year: ['year', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
