/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FundingType
 */
export enum FundingType {
  Credit = 'credit',
  Debit = 'debit',
  Prepaid = 'prepaid',
  ChargeCard = 'chargeCard',
  DeferredDebit = 'deferredDebit',
}

/**
 * Schema for FundingType
 */
export const fundingTypeSchema: Schema<FundingType> = stringEnum(FundingType);
