/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** An object containing information returned by the issuer. */
export interface Issuer {
  /** A code returned by the card issuer for a successful authorization. Used in reconciliation and dispute management. */
  authorizationCode: string;
}

export const issuerSchema: Schema<Issuer> = object({
  authorizationCode: ['authorizationCode', string()],
});
