/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object containing information returned by the issuer. */
export interface Issuer {
  /** A code returned by the card issuer for a successful authorization. Used in reconciliation and dispute management. */
  authorizationCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const issuerSchema: Schema<Issuer> = typedExpandoObject(
  { authorizationCode: ['authorizationCode', string()] },
  'additionalProperties',
  optional(unknown())
);
