/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LastEvent
 */
export enum LastEvent {
  AuthorizationRequested = 'authorizationRequested',
  AuthorizationSucceeded = 'authorizationSucceeded',
  AuthorizationRefused = 'authorizationRefused',
  AuthorizationFailed = 'authorizationFailed',
  AuthorizationTimedOut = 'authorizationTimedOut',
  SaleRequested = 'saleRequested',
  SaleSucceeded = 'saleSucceeded',
  SaleRefused = 'saleRefused',
  SaleFailed = 'saleFailed',
  SaleTimedOut = 'saleTimedOut',
  SettlementRequested = 'settlementRequested',
  SettlementRequestSubmitted = 'settlementRequestSubmitted',
  SettlementFailed = 'settlementFailed',
  SettlementTimedOut = 'settlementTimedOut',
  RefundRequested = 'refundRequested',
  RefundRequestSubmitted = 'refundRequestSubmitted',
  RefundFailed = 'refundFailed',
  RefundTimedOut = 'refundTimedOut',
  CancellationRequested = 'cancellationRequested',
  CancellationRequestSubmitted = 'cancellationRequestSubmitted',
  CancellationFailed = 'cancellationFailed',
  CancellationTimedOut = 'cancellationTimedOut',
  ReversalRequested = 'reversalRequested',
  ReversalRequestSubmitted = 'reversalRequestSubmitted',
  ReversalFailed = 'reversalFailed',
  ReversalTimedOut = 'reversalTimedOut',
}

/**
 * Schema for LastEvent
 */
export const lastEventSchema: Schema<LastEvent> = stringEnum(LastEvent);
