/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Next, nextSchema } from './next.js';
import { Self1, self1Schema } from './self1.js';

/** links to the pages. */
export interface Links1 {
  /** Self link to the page. */
  self: Self1;
  /** Next page link if the response contains more pages. */
  next?: Next;
  additionalProperties?: Record<string, unknown>;
}

export const links1Schema: Schema<Links1> = typedExpandoObject(
  {
    self: ['self', lazy(() => self1Schema)],
    next: ['next', optional(lazy(() => nextSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
