/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { PaymentsCancel, paymentsCancelSchema } from './paymentsCancel.js';
import {
  PaymentsPartialSettle,
  paymentsPartialSettleSchema,
} from './paymentsPartialSettle.js';
import { PaymentsSettle, paymentsSettleSchema } from './paymentsSettle.js';
import { Self, selfSchema } from './self.js';

/** Self link and next action links.The Next action links are dependent on the lastEvent, refer to 'query for historical payments Response' section for more details. */
export interface Links3 {
  /** Self link to the page. */
  self: Self;
  /** Next action links. */
  paymentsCancel?: PaymentsCancel;
  /** Next action links. */
  paymentsSettle?: PaymentsSettle;
  /** Next action links. */
  paymentsPartialSettle?: PaymentsPartialSettle;
}

export const links3Schema: Schema<Links3> = object({
  self: ['self', lazy(() => selfSchema)],
  paymentsCancel: [
    'payments:cancel',
    optional(lazy(() => paymentsCancelSchema)),
  ],
  paymentsSettle: [
    'payments:settle',
    optional(lazy(() => paymentsSettleSchema)),
  ],
  paymentsPartialSettle: [
    'payments:partialSettle',
    optional(lazy(() => paymentsPartialSettleSchema)),
  ],
});
