/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { PaymentsCancel, paymentsCancelSchema } from './paymentsCancel.js';
import { PaymentsEvents, paymentsEventsSchema } from './paymentsEvents.js';
import {
  PaymentsPartialSettle,
  paymentsPartialSettleSchema,
} from './paymentsPartialSettle.js';
import { PaymentsSettle, paymentsSettleSchema } from './paymentsSettle.js';
import { Self, selfSchema } from './self.js';

/** Self link and next action links. */
export interface Links {
  /** Self link to the page. */
  self: Self;
  /** Next action links. */
  paymentsCancel?: PaymentsCancel;
  /** Next action links. */
  paymentsEvents?: PaymentsEvents;
  /** Next action links. */
  paymentsSettle?: PaymentsSettle;
  /** Next action links. */
  paymentsPartialSettle?: PaymentsPartialSettle;
}

export const linksSchema: Schema<Links> = object({
  self: ['self', lazy(() => selfSchema)],
  paymentsCancel: [
    'payments:cancel',
    optional(lazy(() => paymentsCancelSchema)),
  ],
  paymentsEvents: [
    'payments:events',
    optional(lazy(() => paymentsEventsSchema)),
  ],
  paymentsSettle: [
    'payments:settle',
    optional(lazy(() => paymentsSettleSchema)),
  ],
  paymentsPartialSettle: [
    'payments:partialSettle',
    optional(lazy(() => paymentsPartialSettleSchema)),
  ],
});
