/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Self2, self2Schema } from './self2.js';

/** link to retrieveByPaymentId. */
export interface Links2 {
  /** Self link to retrieveByPaymentId. */
  self: Self2;
  additionalProperties?: Record<string, unknown>;
}

export const links2Schema: Schema<Links2> = typedExpandoObject(
  { self: ['self', lazy(() => self2Schema)] },
  'additionalProperties',
  optional(unknown())
);
