/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Self2, self2Schema } from './self2.js';

/** link to retrieveByPaymentId. */
export interface Links2 {
  /** Self link to retrieveByPaymentId. */
  self: Self2;
}

export const links2Schema: Schema<Links2> = object({
  self: ['self', lazy(() => self2Schema)],
});
