/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Message
 */
export enum Message {
  EnumPaymentFailedToBeAuthorized = 'Payment failed to be authorized',
  EnumTokenIsUnrecognized = 'Token is unrecognized',
  EnumTheTransactionReferenceIsADuplicate = 'The transaction reference is a duplicate',
  EnumTheTransactionHasAlreadyBeenProcessed = 'The transaction has already been processed',
  EnumCurrencyNotSupported = 'Currency not supported',
}

/**
 * Schema for Message
 */
export const messageSchema: Schema<Message> = stringEnum(Message, true);
