/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NameEnum
 */
export enum NameEnum {
  InternalErrorOccurred = 'internalErrorOccurred',
  TransactionReferenceIsADuplicate = 'transactionReferenceIsADuplicate',
  TransactionHasAlreadyBeenProcessed = 'transactionHasAlreadyBeenProcessed',
  ChannelIsNotSupported = 'channelIsNotSupported',
  CurrencyIsNotSupported = 'currencyIsNotSupported',
  PaymentInstrumentIsNotSupported = 'paymentInstrumentIsNotSupported',
  FieldHasInvalidValue = 'fieldHasInvalidValue',
  FieldIsEmpty = 'fieldIsEmpty',
  CardNumberIsNotRecognized = 'cardNumberIsNotRecognized',
  UnderlyingPaymentInstrumentHasExpired = 'underlyingPaymentInstrumentHasExpired',
  EntityIsNotConfigured = 'entityIsNotConfigured',
}

/**
 * Schema for NameEnum
 */
export const nameEnumSchema: Schema<NameEnum> = stringEnum(NameEnum);
