/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The text that appears on your customer's statement. Used to identify the merchant. */
export interface Narrative {
  /** The first line of the narrative which appears on your customer's statement (24 characters max. If character is not supported it is replaced with a space). */
  line1: string;
  /** Additional details about the payment e.g. order number, telephone number. */
  line2?: string;
  additionalProperties?: Record<string, unknown>;
}

export const narrativeSchema: Schema<Narrative> = typedExpandoObject(
  { line1: ['line1', string()], line2: ['line2', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
