/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** An object that contains identification and further details of the merchant. */
export interface Narrative1 {
  /** First line of text that appears on your customer's statement. */
  line1?: string;
  /** Second line of text that appears on your customer's statement. */
  line2?: string;
}

export const narrative1Schema: Schema<Narrative1> = object({
  line1: ['line1', optional(string())],
  line2: ['line2', optional(string())],
});
