/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** The text that appears on your customer's statement. Used to identify the merchant. */
export interface Narrative {
  /** The first line of the narrative which appears on your customer's statement (24 characters max. If character is not supported it is replaced with a space). */
  line1: string;
  /** Additional details about the payment e.g. order number, telephone number. */
  line2?: string;
}

export const narrativeSchema: Schema<Narrative> = object({
  line1: ['line1', string()],
  line2: ['line2', optional(string())],
});
