/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Next page link if the response contains more pages. */
export interface Next {
  /** Second page as per the pageSize. */
  href?: string;
}

export const nextSchema: Schema<Next> = object({
  href: ['href', optional(string())],
});
