/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Next page link if the response contains more pages. */
export interface Next {
  /** Second page as per the pageSize. */
  href?: string;
  additionalProperties?: Record<string, unknown>;
}

export const nextSchema: Schema<Next> = typedExpandoObject(
  { href: ['href', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
