/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object that contains information about the card number. */
export interface Number3 {
  /** last4Digits of the card number used. */
  last4Digits?: string;
  additionalProperties?: Record<string, unknown>;
}

export const number3Schema: Schema<Number3> = typedExpandoObject(
  { last4Digits: ['last4Digits', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
