/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object that contains information about the card number. */
export interface Number {
  /** The card BIN (Bank Identification Number) is the first 6 or 8 digits of the card number, and can be used to identify the card issuer, the card brand(s) (eg Visa, Cartes Bancaires), and the country. Card BINs are used to route transactions, check card capabilities, and in fraud assessments. */
  cardBin?: string;
  /** The last four digits of the card. Some characters may be obfuscated with a `*` if the PAN length is less than 16 characters. */
  last4Digits?: string;
  additionalProperties?: Record<string, unknown>;
}

export const numberSchema: Schema<Number> = typedExpandoObject(
  {
    cardBin: ['cardBin', optional(string())],
    last4Digits: ['last4Digits', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
