/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** An object that contains information about the card number. */
export interface Number3 {
  /** last4Digits of the card number used. */
  last4Digits?: string;
}

export const number3Schema: Schema<Number3> = object({
  last4Digits: ['last4Digits', optional(string())],
});
