/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OutcomeEnum
 */
export enum OutcomeEnum {
  Authorized = 'authorized',
}

/**
 * Schema for OutcomeEnum
 */
export const outcomeEnumSchema: Schema<OutcomeEnum> = stringEnum(OutcomeEnum);
