/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Outcome1Enum
 */
export enum Outcome1Enum {
  Refused = 'refused',
}

/**
 * Schema for Outcome1Enum
 */
export const outcome1EnumSchema: Schema<Outcome1Enum> = stringEnum(
  Outcome1Enum
);
