/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Outcome
 */
export enum Outcome {
  Authorized = 'authorized',
}

/**
 * Schema for Outcome
 */
export const outcomeSchema: Schema<Outcome> = stringEnum(Outcome);
