/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Outcome1
 */
export enum Outcome1 {
  Refused = 'refused',
}

/**
 * Schema for Outcome1
 */
export const outcome1Schema: Schema<Outcome1> = stringEnum(Outcome1);
