/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Card, cardSchema } from './card.js';
import { Type2Enum, type2EnumSchema } from './type2Enum.js';

/** The payment instrument supplied in the authorization request. */
export interface PaymentInstrument {
  /** The type of payment instrument supplied in the authorization request. */
  type?: Type2Enum;
  /** An object that contains information about the card used. */
  card?: Card;
}

export const paymentInstrumentSchema: Schema<PaymentInstrument> = object({
  type: ['type', optional(type2EnumSchema)],
  card: ['card', optional(lazy(() => cardSchema))],
});
