/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Card, cardSchema } from './card.js';
import { Type2, type2Schema } from './type2.js';

/** The payment instrument supplied in the authorization request. */
export interface PaymentInstrument {
  /** The type of payment instrument supplied in the authorization request. */
  type?: Type2;
  /** An object that contains information about the card used. */
  card?: Card;
  additionalProperties?: Record<string, unknown>;
}

export const paymentInstrumentSchema: Schema<PaymentInstrument> = typedExpandoObject(
  {
    type: ['type', optional(type2Schema)],
    card: ['card', optional(lazy(() => cardSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
