/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Next action links. */
export interface PaymentsSettle {
  /** Next action links. */
  href?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsSettleSchema: Schema<PaymentsSettle> = typedExpandoObject(
  { href: ['href', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
