/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Card3, card3Schema } from './card3.js';
import { Type5Enum, type5EnumSchema } from './type5Enum.js';

/** An object that contains information about the payment type. */
export interface PaymentInstrument2 {
  /** An object that contains information about the payment type. */
  type?: Type5Enum;
  /** An object that contains information about the card used. */
  card?: Card3;
}

export const paymentInstrument2Schema: Schema<PaymentInstrument2> = object({
  type: ['type', optional(type5EnumSchema)],
  card: ['card', optional(lazy(() => card3Schema))],
});
