/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Card3, card3Schema } from './card3.js';
import { Type5, type5Schema } from './type5.js';

/** An object that contains information about the payment type. */
export interface PaymentInstrument2 {
  /** An object that contains information about the payment type. */
  type?: Type5;
  /** An object that contains information about the card used. */
  card?: Card3;
  additionalProperties?: Record<string, unknown>;
}

export const paymentInstrument2Schema: Schema<PaymentInstrument2> = typedExpandoObject(
  {
    type: ['type', optional(type5Schema)],
    card: ['card', optional(lazy(() => card3Schema))],
  },
  'additionalProperties',
  optional(unknown())
);
