/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Next action links. */
export interface PaymentsSettle {
  /** Next action links. */
  href?: string;
}

export const paymentsSettleSchema: Schema<PaymentsSettle> = object({
  href: ['href', optional(string())],
});
