/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Next action links. */
export interface PaymentsPartialSettle {
  /** Next action links. */
  href?: string;
}

export const paymentsPartialSettleSchema: Schema<PaymentsPartialSettle> = object(
  { href: ['href', optional(string())] }
);
