/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Embedded, embeddedSchema } from './embedded.js';
import { Links1, links1Schema } from './links1.js';

export interface PqQuerybydaterange200Response {
  /** links to the pages. */
  links: Links1;
  embedded: Embedded;
  additionalProperties?: Record<string, unknown>;
}

export const pqQuerybydaterange200ResponseSchema: Schema<PqQuerybydaterange200Response> = typedExpandoObject(
  {
    links: ['_links', lazy(() => links1Schema)],
    embedded: ['_embedded', lazy(() => embeddedSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
