/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Embedded1, embedded1Schema } from './embedded1.js';
import { Links3, links3Schema } from './links3.js';

export interface PqQueryhistoricalpayments200Response {
  /** Self link and next action links.The Next action links are dependent on the lastEvent, refer to 'query for historical payments Response' section for more details. */
  links: Links3;
  embedded: Embedded1;
  additionalProperties?: Record<string, unknown>;
}

export const pqQueryhistoricalpayments200ResponseSchema: Schema<PqQueryhistoricalpayments200Response> = typedExpandoObject(
  {
    links: ['_links', lazy(() => links3Schema)],
    embedded: ['_embedded', lazy(() => embedded1Schema)],
  },
  'additionalProperties',
  optional(unknown())
);
