/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Embedded, embeddedSchema } from './embedded.js';
import { Links1, links1Schema } from './links1.js';

export interface PqQuerybydaterange200Response {
  /** links to the pages. */
  links: Links1;
  embedded: Embedded;
}

export const pqQuerybydaterange200ResponseSchema: Schema<PqQuerybydaterange200Response> = object(
  {
    links: ['_links', lazy(() => links1Schema)],
    embedded: ['_embedded', lazy(() => embeddedSchema)],
  }
);
