/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Value2, value2Schema } from './value2.js';

export interface ReversalRequested {
  /** Worldpay has received your reversal request. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** An object that contains the amount and currency requested for reversal. */
  value?: Value2;
  additionalProperties?: Record<string, unknown>;
}

export const reversalRequestedSchema: Schema<ReversalRequested> = typedExpandoObject(
  {
    eventName: ['eventName', string()],
    timestamp: ['timestamp', optional(string())],
    value: ['value', optional(lazy(() => value2Schema))],
  },
  'additionalProperties',
  optional(unknown())
);
