/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Value2, value2Schema } from './value2.js';

export interface ReversalRequested {
  /** Worldpay has received your reversal request. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** An object that contains the amount and currency requested for reversal. */
  value?: Value2;
  /** Unique identifier generated by us for a single instance of an interaction (command) with the Worldpay API. */
  commandId?: string;
}

export const reversalRequestedSchema: Schema<ReversalRequested> = object({
  eventName: ['eventName', string()],
  timestamp: ['timestamp', optional(string())],
  value: ['value', optional(lazy(() => value2Schema))],
  commandId: ['commandId', optional(string())],
});
