/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { OutcomeEnum, outcomeEnumSchema } from './outcomeEnum.js';

export interface SaleSucceeded {
  /** Your authorization request was successfully approved by the card issuer. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** Outcome of the event. For every requested event there can be a successful or refused event outcome. */
  outcome?: OutcomeEnum;
  /** Unique identifier generated by us for a single instance of an interaction (command) with the Worldpay API. */
  commandId?: string;
}

export const saleSucceededSchema: Schema<SaleSucceeded> = object({
  eventName: ['eventName', string()],
  timestamp: ['timestamp', optional(string())],
  outcome: ['outcome', optional(outcomeEnumSchema)],
  commandId: ['commandId', optional(string())],
});
