/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Error, errorSchema } from './error.js';

export interface SaleFailed {
  /** Your sale request failed. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** All Failed events return error object with name and message. */
  error?: Error;
  /** Unique identifier generated by us for a single instance of an interaction (command) with the Worldpay API. */
  commandId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const saleFailedSchema: Schema<SaleFailed> = typedExpandoObject(
  {
    eventName: ['eventName', string()],
    timestamp: ['timestamp', optional(string())],
    error: ['error', optional(lazy(() => errorSchema))],
    commandId: ['commandId', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
