/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Outcome1, outcome1Schema } from './outcome1.js';

export interface SaleRefused {
  /** Your sale request was refused by the card issuer. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** Outcome of the event. For every requested event there can be a successful or refused event outcome. */
  outcome?: Outcome1;
  /** The response code, used to identify the refusal reason. */
  code?: string;
  /** The description of the refusal reason. */
  description?: string;
  additionalProperties?: Record<string, unknown>;
}

export const saleRefusedSchema: Schema<SaleRefused> = typedExpandoObject(
  {
    eventName: ['eventName', string()],
    timestamp: ['timestamp', optional(string())],
    outcome: ['outcome', optional(outcome1Schema)],
    code: ['code', optional(string())],
    description: ['description', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
