/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Outcome, outcomeSchema } from './outcome.js';

export interface SaleSucceeded {
  /** Your authorization request was successfully approved by the card issuer. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** Outcome of the event. For every requested event there can be a successful or refused event outcome. */
  outcome?: Outcome;
  additionalProperties?: Record<string, unknown>;
}

export const saleSucceededSchema: Schema<SaleSucceeded> = typedExpandoObject(
  {
    eventName: ['eventName', string()],
    timestamp: ['timestamp', optional(string())],
    outcome: ['outcome', optional(outcomeSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
