/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { Outcome1Enum, outcome1EnumSchema } from './outcome1Enum.js';

export interface SaleRefused {
  /** Your sale request was refused by the card issuer. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  /** Outcome of the event. For every requested event there can be a successful or refused event outcome. */
  outcome?: Outcome1Enum;
  /** The response code, used to identify the refusal reason. */
  code?: string;
  /** The description of the refusal reason. */
  description?: string;
  /** Unique identifier generated by us for a single instance of an interaction (command) with the Worldpay API. */
  commandId?: string;
}

export const saleRefusedSchema: Schema<SaleRefused> = object({
  eventName: ['eventName', string()],
  timestamp: ['timestamp', optional(string())],
  outcome: ['outcome', optional(outcome1EnumSchema)],
  code: ['code', optional(string())],
  description: ['description', optional(string())],
  commandId: ['commandId', optional(string())],
});
