/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** An object containing information returned by the card scheme. */
export interface Scheme {
  /** The reference returned by the scheme for this particular payment authorization. */
  reference: string;
}

export const schemeSchema: Schema<Scheme> = object({
  reference: ['reference', string()],
});
