/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object containing information returned by the card scheme. */
export interface Scheme {
  /** The reference returned by the scheme for this particular payment authorization. */
  reference: string;
  additionalProperties?: Record<string, unknown>;
}

export const schemeSchema: Schema<Scheme> = typedExpandoObject(
  { reference: ['reference', string()] },
  'additionalProperties',
  optional(unknown())
);
