/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Self link to the page. */
export interface Self1 {
  /** First page as per the pageSize. */
  href?: string;
}

export const self1Schema: Schema<Self1> = object({
  href: ['href', optional(string())],
});
