/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Self link to retrieveByPaymentId. */
export interface Self2 {
  /** RetrieveByPaymentId provides event history and next action links. */
  href?: string;
}

export const self2Schema: Schema<Self2> = object({
  href: ['href', optional(string())],
});
