/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Self link to the page. */
export interface Self1 {
  /** First page as per the pageSize. */
  href?: string;
  additionalProperties?: Record<string, unknown>;
}

export const self1Schema: Schema<Self1> = typedExpandoObject(
  { href: ['href', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
