/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Self link to retrieveByPaymentId. */
export interface Self2 {
  /** RetrieveByPaymentId provides event history and next action links. */
  href?: string;
  additionalProperties?: Record<string, unknown>;
}

export const self2Schema: Schema<Self2> = typedExpandoObject(
  { href: ['href', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
