/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Self link to the page. */
export interface Self {
  /** Self link to the page. */
  href?: string;
}

export const selfSchema: Schema<Self> = object({
  href: ['href', optional(string())],
});
