/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Type, typeSchema } from './type.js';
import { Value, valueSchema } from './value.js';

export interface SettlementRequested {
  /** Worldpay has received your settlement request. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  type?: Type;
  /** Your settlement reference */
  settlementReference?: string;
  /** An object that contains the amount and currency requested for settlement. */
  value?: Value;
  additionalProperties?: Record<string, unknown>;
}

export const settlementRequestedSchema: Schema<SettlementRequested> = typedExpandoObject(
  {
    eventName: ['eventName', string()],
    timestamp: ['timestamp', optional(string())],
    type: ['type', optional(typeSchema)],
    settlementReference: ['settlementReference', optional(string())],
    value: ['value', optional(lazy(() => valueSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
