/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';
import { Value, valueSchema } from './value.js';

export interface SettlementRequested {
  /** Worldpay has received your settlement request. */
  eventName: string;
  /** The ISO 8601 date-time at which the event was created. */
  timestamp?: string;
  type?: TypeEnum;
  /** Your settlement reference */
  settlementReference?: string;
  /** An object that contains the amount and currency requested for settlement. */
  value?: Value;
  /** Unique identifier generated by us for a single instance of an interaction (command) with the Worldpay API. */
  commandId?: string;
}

export const settlementRequestedSchema: Schema<SettlementRequested> = object({
  eventName: ['eventName', string()],
  timestamp: ['timestamp', optional(string())],
  type: ['type', optional(typeEnumSchema)],
  settlementReference: ['settlementReference', optional(string())],
  value: ['value', optional(lazy(() => valueSchema))],
  commandId: ['commandId', optional(string())],
});
