/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionTypeEnum
 */
export enum TransactionTypeEnum {
  OneTime = 'oneTime',
  CardOnFile = 'cardOnFile',
  Recurring = 'recurring',
}

/**
 * Schema for TransactionTypeEnum
 */
export const transactionTypeEnumSchema: Schema<TransactionTypeEnum> = stringEnum(
  TransactionTypeEnum
);
