/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionType1
 */
export enum TransactionType1 {
  OneTime = 'oneTime',
  CardOnFile = 'cardOnFile',
  Recurring = 'recurring',
}

/**
 * Schema for TransactionType1
 */
export const transactionType1Schema: Schema<TransactionType1> = stringEnum(
  TransactionType1,
  true
);
