/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionType1Enum
 */
export enum TransactionType1Enum {
  OneTime = 'oneTime',
  CardOnFile = 'cardOnFile',
  Recurring = 'recurring',
}

/**
 * Schema for TransactionType1Enum
 */
export const transactionType1EnumSchema: Schema<TransactionType1Enum> = stringEnum(
  TransactionType1Enum
);
