/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionType
 */
export enum TransactionType {
  OneTime = 'oneTime',
  CardOnFile = 'cardOnFile',
  Recurring = 'recurring',
}

/**
 * Schema for TransactionType
 */
export const transactionTypeSchema: Schema<TransactionType> = stringEnum(
  TransactionType,
  true
);
