/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type
 */
export enum Type {
  FullSettlement = 'fullSettlement',
  PartialSettlement = 'partialSettlement',
}

/**
 * Schema for Type
 */
export const typeSchema: Schema<Type> = stringEnum(Type);
