/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type5Enum
 */
export enum Type5Enum {
  EnumCardplain = 'card/plain',
  EnumCardnetwork = 'card/network',
  EnumCardnetworkToken = 'card/networkToken',
  EnumCardnetworkTokenapplepay = 'card/networkToken+applepay',
  EnumCardnetworkTokengooglepay = 'card/networkToken+googlepay',
  EnumCardplainmasked = 'card/plain+masked',
}

/**
 * Schema for Type5Enum
 */
export const type5EnumSchema: Schema<Type5Enum> = stringEnum(Type5Enum);
