/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type3Enum
 */
export enum Type3Enum {
  EnumCardnetworkToken = 'card/networkToken',
  EnumCardplainmasked = 'card/plain+masked',
}

/**
 * Schema for Type3Enum
 */
export const type3EnumSchema: Schema<Type3Enum> = stringEnum(Type3Enum);
