/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type2Enum
 */
export enum Type2Enum {
  EnumCardplain = 'card/plain',
  EnumCardnetwork = 'card/network',
  EnumCardnetworkToken = 'card/networkToken',
  EnumCardnetworkTokenapplepay = 'card/networkToken+applepay',
  EnumCardnetworkTokengooglepay = 'card/networkToken+googlepay',
  EnumCardplainmasked = 'card/plain+masked',
}

/**
 * Schema for Type2Enum
 */
export const type2EnumSchema: Schema<Type2Enum> = stringEnum(Type2Enum);
