/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type2
 */
export enum Type2 {
  EnumCardplain = 'card/plain',
  EnumCardnetwork = 'card/network',
  EnumCardnetworkToken = 'card/networkToken',
  EnumCardnetworkTokenapplepay = 'card/networkToken+applepay',
  EnumCardnetworkTokengooglepay = 'card/networkToken+googlepay',
  EnumCardplainmasked = 'card/plain+masked',
}

/**
 * Schema for Type2
 */
export const type2Schema: Schema<Type2> = stringEnum(Type2, true);
