/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type1
 */
export enum Type1 {
  FullRefund = 'fullRefund',
  PartialRefund = 'partialRefund',
}

/**
 * Schema for Type1
 */
export const type1Schema: Schema<Type1> = stringEnum(Type1);
