/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AccountUpdaterMessage,
  accountUpdaterMessageSchema,
} from './accountUpdaterMessage.js';
import { Card1, card1Schema } from './card1.js';
import { Type3, type3Schema } from './type3.js';

/** The payment instrument supplied in the authorization request. */
export interface UpdatedPaymentInstrument {
  /** The type of payment instrument supplied in the authorization request. */
  type?: Type3;
  /** An object that contains information about the card used. */
  card?: Card1;
  /** Details on the type of payment instrument update. */
  accountUpdaterMessage?: AccountUpdaterMessage;
  additionalProperties?: Record<string, unknown>;
}

export const updatedPaymentInstrumentSchema: Schema<UpdatedPaymentInstrument> = typedExpandoObject(
  {
    type: ['type', optional(type3Schema)],
    card: ['card', optional(lazy(() => card1Schema))],
    accountUpdaterMessage: [
      'accountUpdaterMessage',
      optional(accountUpdaterMessageSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
