/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  AccountUpdaterMessageEnum,
  accountUpdaterMessageEnumSchema,
} from './accountUpdaterMessageEnum.js';
import { Card1, card1Schema } from './card1.js';
import { Type3Enum, type3EnumSchema } from './type3Enum.js';

/** The payment instrument supplied in the authorization request. */
export interface UpdatedPaymentInstrument {
  /** The type of payment instrument supplied in the authorization request. */
  type?: Type3Enum;
  /** An object that contains information about the card used. */
  card?: Card1;
  /** Details on the type of payment instrument update. */
  accountUpdaterMessage?: AccountUpdaterMessageEnum;
}

export const updatedPaymentInstrumentSchema: Schema<UpdatedPaymentInstrument> = object(
  {
    type: ['type', optional(type3EnumSchema)],
    card: ['card', optional(lazy(() => card1Schema))],
    accountUpdaterMessage: [
      'accountUpdaterMessage',
      optional(accountUpdaterMessageEnumSchema),
    ],
  }
);
