/**
 * Payment QueriesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object that contains payment amount and currency. */
export interface Value3 {
  /** This is a whole number including the currency exponent (e.g. GBP has an exponent of 2, so for £2.50 supply:`250`). */
  amount: number;
  /** The 3 digit currency code. */
  currency: string;
  additionalProperties?: Record<string, unknown>;
}

export const value3Schema: Schema<Value3> = typedExpandoObject(
  { amount: ['amount', number()], currency: ['currency', string()] },
  'additionalProperties',
  optional(unknown())
);
